name: DLIO Profiler Build and Test

on:
  push:
    branches: [dev ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04,  ubuntu-22.04]
        dir: ["clone", "github"]
        perm: ["root", "user"]
    name: ${{ matrix.os }}-${{ matrix.dir }}-${{ matrix.perm }}
    runs-on: ${{ matrix.os }}
    env:
      CC: gcc
      CXX: g++
      DIR: ${{ matrix.dir }}
      PERM: ${{ matrix.perm }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install additional packages
        run: |
          sudo apt-get update
          sudo apt-get install gcc g++ libtool-bin openmpi-bin libopenmpi-dev
          sudo apt-get install python3 python3-pip
      - name: Build from ${{ matrix.dir }} on ${{ matrix.perm }}
        run: |
          LOC=.
          if [[ $DIR == 'github' ]]; then
            LOC=git+https://github.com/hariharan-devarajan/dlio-profiler.git@dev
          fi
          if [[ $PERM == 'user' ]]; then
            export DLIO_LOGGER_USER=1
            echo pip install -v ${LOC}
            pip install -v ${LOC}
          else
             echo pip install -v ${LOC}
             sudo pip install -v ${LOC}
          fi